### ISSUE TITLE
merge experiment and experiment_simple

### ISSUE THREAD

**Issue by chrishokamp** [qe-team/marmot#10]
Some nagging :-)

fb6efeef462bf637446ab63a72abf0108c2f6023 creates duplicate code, which is completely untested. This should go in a branch, or in a fork of this repo, which can then be merged when the code is ready -- see [gitlab flow](https://about.gitlab.com/2014/09/29/gitlab-flow/). 

Also, [using spaces around parameters and in comprehensions](https://github.com/qe-team/marmot/commit/e82308fb99c45d6d79877bece757c69c9278b294#diff-315a831eb1ba39d77fbc72dd6ff48dc0R91), and indenting with 2 spaces instead of 4 does not follow the pep8 style guidelines. Since the philosophy of python is 'there's only one way to do it', we should follow the style rules. There are good extensions for vim, pycharm, etc..., which check pep8 style automatically, that's what I use. 

Finally, the new python print function is an actual function, not a keyword. That means that [lines like this](https://github.com/qe-team/marmot/commit/e82308fb99c45d6d79877bece757c69c9278b294#diff-315a831eb1ba39d77fbc72dd6ff48dc0L77) will break on python3, and we will have to fix them later. 

I only mention this stuff because I want to avoid the problems that other academic open-source projects have, where the code is messy and impossible to read. Right now at the beginning it is much easier to fix than it will be later. Feel free to criticise my code as well ;-)

**Comment by varvara-l** [comment]
OK, I made a new branch. Life is pain...

**Comment by varvara-l** [comment]
done
