### ISSUE TITLE
push sample data for experiment/test/test_data/test_config.yaml

### ISSUE THREAD

**Issue by chrishokamp** [qe-team/marmot#2]
The tests are missing sample data -- we should push small samples to the repo so that the tests run out-of-the-box.

I'm referring to the config file here:
https://github.com/qe-team/marmot/blob/master/marmot/experiment/test/test_data/test_config.yaml#L48-L50
https://github.com/qe-team/marmot/blob/master/marmot/experiment/test/test_data/test_config.yaml#L60-L62

**Comment by chrishokamp** [comment]
you could also just use [1] for the tests that require these feature extractors. It's ok to create another test suite in experiment/test if that's easier. 

[1] https://github.com/qe-team/marmot/blob/master/marmot/experiment/en_es_data/en_es_config.yaml

**Comment by varvara-l** [comment]
Added links to sample data from https://github.com/qe-team/marmot/blob/master/marmot/experiment/en_es_data/en_es_config.yaml.
But we are not really checking the output of these feature extractors in the tests, so for now it won't make any difference. I'll add some new tests.

**Comment by varvara-l** [comment]
Done
