### ISSUE TITLE
binarizing alignment features takes a long time

### ISSUE THREAD

**Issue by chrishokamp** [qe-team/marmot#22]
why does this take so long? Is it just because there are so many possible values? what is the bottleneck in the process?

**Comment by varvara-l** [comment]
I don't know. There are similar complaints (http://stackoverflow.com/questions/20158624/labelbinarizer-takes-forever). But when there are many values, it should just take much space, not time.

**Comment by chrishokamp** [comment]
Ok let's close for now - I think part of it was the bug we fixed yesterday
