### ISSUE TITLE
build_context_creators and build_feature_extractors (in experiment_utils.py)

### ISSUE THREAD

**Issue by varvara-l** [qe-team/marmot#6]
It looks like build_feature_extractors (https://github.com/qe-team/marmot/blob/master/marmot/experiment/experiment_utils.py#L124) does the same as build_context_creators + build_context_creator.

Is there any sense in having both functions, or they can be merged into one?

I'm just thinking of adding another object which will be built almost like context creators and feature extractors. It looks more elegant to have a function build_object for all than to create the third almost identical function.

**Comment by chrishokamp** [comment]
the difference is that build_context_creator lets you do it with a single
object instead of a list, and context creator also handles the
'function_output' flag. I will take a look and see how the two functions
could be combined.

**Comment by varvara-l** [comment]
I've done that in "simple" branch: experiment.import_utils.build_object and build_objects

**Comment by varvara-l** [comment]
build_context_creator and build_feature_extractors replaced with build_objects
