### ISSUE TITLE
experiment_utils doesn't allow args to be passed to get_features

### ISSUE THREAD

**Issue by chrishokamp** [qe-team/marmot#8]
some feature extractors, such as the word2vec window feature extractor, have additional keyword args in get_features. experiment_utils currently doesn't allow us to access these args from map_feature_extractor, so we're forced to use the default arguments. 

[code](https://github.com/qe-team/marmot/blob/master/marmot/experiment/experiment_utils.py#L138-L141)

**Comment by varvara-l** [comment]
We need to think of a new feature extractors declaration in config.
There is a field "args", which are args for feature extractor **init**, there should be another set of arguments - for the get_features function of the feature extractor.

Now:
- module: marmot.features.alignment_feature_extractor.AlignmentFeatureExtractor
  args:
  - ''
  - !join ../examples/word_level_quality_estimation/data/en_es/europarl.1000.en
  - !join ../examples/word_level_quality_estimation/data/en_es/europarl.1000.es

Should be:
- module: marmot.features.alignment_feature_extractor.AlignmentFeatureExtractor
  args:
  - ''
  - !join ../examples/word_level_quality_estimation/data/en_es/europarl.1000.en
  - !join ../examples/word_level_quality_estimation/data/en_es/europarl.1000.es
    args_get_features:
  - 
    -
    -

**Comment by varvara-l** [comment]
The question is -- are we going to call get_features with different parameters in one run. In other words, do we already know these parameters during the initialisation, or not.

If we do, they should be specified in **init**, and removed from get_features keyword arguments.

I can't think of situations when we need to call the same feature extractor once with different arguments, so it seems reasonable to get rid of keyword args.

**Comment by varvara-l** [comment]
Fixed in all existing features.
All parameters of new feature extractors should be specified in **init**.
